### ISSUE TITLE
make: don't know how to make cw-ec2. Stop

### ISSUE THREAD

**Issue by nbari** [cperciva/bsdec2-image-upload#1]
While doing an:

```
# cd /usr/src && make buildworld buildkernel
# cd /usr/src/release && make ec2ami
```

This is what I got:

```
# make ec2ami
make: don't know how to make cw-ec2. Stop

make: stopped in /usr/src/release
```

Port `/usr/ports/net/bsdec2-image-upload` already installed, any idea of what could it be wrong:

How should I specify the AWS_KEY, SECRET, BUCKET on `/etc/make.conf` ?

thanks in advance

**Comment by cperciva** [comment]
You need WITH_CLOUDWARE=YES.

**Comment by nbari** [comment]
Many thanks, I am using now WITH_CLOUDWARE=YES but getting this::

```
Uploading /usr/src/release/ec2.raw to
http://freebsd-nbari.s3.amazonaws.com/1f75cce4ae1ed42129d2153a81378ac3/
in 154 part(s).*** Signal 13
```

If I upload the `ec2.raw` by other methods is ok or further task need to be done

**Comment by nbari** [comment]
It seems to be that only us-east zones working, I give a try to us-east-1a but now I am getting this:

```
part(s).bsdec2-image-upload: SSL request failed: DNS lookup failed
bsdec2-image-upload: PUT failed 
bsdec2-image-upload: Failure uploading disk image
*** Error code 1
```

By other hand, I am trying with `ec2-import-volume ec2.raw -f raw -b my-bucket -z us-east-1a` and currently uploading.

but If I try using `ec2-import-instance -f raw -a x86_64 -b my-bucket` I get something like: 

```
Client.Unsupported: No bootable partition found. (Service: AmazonEC2; Status Code: 400; Error Code: Unsupported; Request ID: 41c8270b-60d1-48ad-bd7b-683c6c55ea84)
```

So once I could upload the volume, how to use it, any idea?
