### ISSUE TITLE
Support for HTTP/1.1 307 Temporary Redirect

### ISSUE THREAD

**Issue by aronemil** [cperciva/bsdec2-image-upload#11]
Hello Colin,
Hope this is detailed enough, when not, let me know.
Thanks for sharing your work with us!
Aron

root@hostname:~ # bsdec2-image-upload /pfsense.img "pfSense" "pfSense" eu-central-1 fra-redacted /home/myuser/awskey
Uploading /pfsense.img to
http://fra-redacted.s3.amazonaws.com/592562b2657f4d84db60f4c899eb57f5/
in 1127 part(s).bsdec2-image-upload: S3 request failed:
HTTP/1.1 307 Temporary Redirect
x-amz-bucket-region: eu-central-1
x-amz-request-id: F51174106260C689
x-amz-id-2: 5nfrlsdBFMWLgNrf2nCKctAccAbpAtV7f4LJQrzZPQR92kXNsshW27XwAFI+bJLKoEigs/VcJVs=
Location: https://fra-redacted.s3.eu-central-1.amazonaws.com/592562b2657f4d84db60f4c899eb57f5/part0
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Sat, 30 Jan 2021 12:59:03 GMT
Connection: close
Server: AmazonS3

1c0
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>TemporaryRedirect</Code><Message>Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.</Message><Endpoint>fra-redacted.s3.eu-central-1.amazonaws.com</Endpoint><Bucket>fra-redacted</Bucket><RequestId>F51174106260C689</RequestId><HostId>5nfrlsdBFMWLgNrf2nCKctAccAbpAtV7f4LJQrzZPQR92kXNsshW27XwAFI+bJLKoEigs/VcJVs=</HostId></Error>
0

S3 PUT failed 1 times: /592562b2657f4d84db60f4c899eb57f5/part0

**Comment by cperciva** [comment]
Sigh, S3 is being silly.  I don't think we need to support 307s though; we just need to put the region into the HTTP request so that S3 knows that we really are sending it to the right place.  I'll try to find time to make the necessary change soon.

**Comment by aronemil** [comment]
My workaround was to doctor with the /etc/hosts file to directly contact the IP that belongs to the regional endpoint for S3.

**Comment by cperciva** [comment]
Oh, the traffic was actually going to the wrong place?  That's a different bug than I thought it was then.  Can you elaborate -- where was the utility trying to send the requests?

**Comment by aronemil** [comment]
There is a central endpoint for S3, and also regional ones.

The central one seems to be the endpoint hardcoded in your code. (via DNS of course).
When you create your S3 bucket in one the regions, this will be firstly only available via the regional endpoint and can take up to 24 hours to work without an 307 redirection. But apparently the central endpoint is not completely unaware of the new bucket and tries to solve this via the mentioned redirect. 

So the idea was to make your code directly contact the regional endpoint via below DNS "hack".

This was the line in my hosts file:
#52.219.74.69 redacted.s3.amazonaws.com

Non-authoritative answer:
69.74.219.52.in-addr.arpa	name = s3-r-w.eu-central-1.amazonaws.com.

While the real IP for my S3 bucket endpoint was (via public DNS): 52.219.72.109

Another option would be to give a hint for your utility. E.g.: with --region parameter, so the regional endpoint can be generated and used in such cases.

**Comment by cperciva** [comment]
Thanks, should be fixed by d8ea5c1e62ad8674b2a3b0b796e909fe724f232c.

**Comment by aronemil** [comment]
Thanks a lot, Collin!
I wish I would be this progressive with my project :)

**Comment by cperciva** [comment]
Having people sponsoring my FreeBSD/EC2 work (https://www.patreon.com/cperciva) encourages me to spend time to address issues like this. ;-)
