### ISSUE TITLE
Provide option to use AWS session tokens

### ISSUE THREAD

**Issue by statseeker** [cperciva/bsdec2-image-upload#17]
thanks for creating a great tool to upload and build AMI's,

We are wanting to use MFA in AWS and still contiinue to use this utility, however enabling MFA prevents us from using this tool as it does not support security session tokens.

Would it be possible to add this as an option when using this CLI tool 

Thanks and appreciate all the great work

**Comment by cperciva** [comment]
Possible?  Absolutely.  But I don't have any code laying around for using MFA on AWS APIs, so it's not likely that I'll have time to do this on a volunteer basis any time soon.  Is your company interested in funding this work?

**Comment by statseeker** [comment]
Hi Colin,

That could be an option, what sort of cost would it be to get this added to the tool.

Thanks

**Comment by cperciva** [comment]
It shouldn't take too long -- probably just two days to write and test it.  And I'll give you a discount assuming you're ok with the work remaining open source under the same license. :-)

Can you send me an email at cperciva@freebsd.org to discuss details?

**Comment by cperciva** [comment]
Closing this as OP indicated via email that they made their own changes.
