### ISSUE TITLE
bsdec2-image-upload: SSL request failed: Name on SSL certificate does not match server

### ISSUE THREAD

**Issue by nilsalex** [cperciva/bsdec2-image-upload#4]
> root@aws:/usr/src/release # make ec2ami
/usr/local/bin/bsdec2-image-upload  --sriov --ena  /usr/src/release/ec2.raw  "FreeBSD 11.1-RELEASE-amd64"  "FreeBSD 11.1-RELEASE-amd64"  eu-central-1 mybucket /home/ec2-user/.aws/secret
Uploading /usr/src/release/ec2.raw to
http://mybucket.s3.amazonaws.com/07754ea9b86ddecacb939ad99f8168d6/
in 205 part(s).bsdec2-image-upload: SSL request failed: Name on SSL certificate does not match server
bsdec2-image-upload: PUT failed
bsdec2-image-upload: Failure uploading disk image
*** Error code 1
Stop.
make: stopped in /usr/src/release
root@aws:/usr/src/release # 

I have ca_root_nss installed and the file

> /usr/local/share/certs/ca-root-nss.crt

 is present.

Do I miss a certificate or is something broken?

**Comment by cperciva** [comment]
Looks like my SSL code is getting confused because Amazon has `s3.eu-central-1.amazonaws.com` as the CN and `s3-eu-central-1.amazonaws.com` as an alternative name; my code in `lib/util/sslreq.c` is only checking the CN.

Patches welcome. ;-)

**Comment by nilsalex** [comment]
(Answer to the comment on the pull request)

Yes hard-coding is not nice, that was just how I fixed the problem for me and for now.

>  I'm also not convinced that the fact that a "dotted" name is being advertised (as opposed to only a "dashed" name) necessarily means that the CN on the TLS certificate will be the "dotted" form.

I inspected the different certificates and this is the way it's behaving now: CN in the dotted form for regions with dotted endpoint names, CN in dashed form for regions with only dashed endpoint names.

Edit: Nevermind, I missed the alternative names. As you already said there we have e.g. *.s3-eu-central-1.amazonaws.com. lib/util/sslreq.c should take these into account, yes.

**Comment by nilsalex** [comment]
Why not use `X509_check_host` from `<openssl/x509v3.h>`?

`if (X509_check_host(cert, host, sizeof(host), 0, NULL)) {
return "Name on SSL certificate does not match server";}`

**Comment by cperciva** [comment]
On 08/09/17 08:12, nilsalex wrote:
> Why not use |X509_check_host| from |<openssl/x509v3.h>|?

Because I didn't know it existed. ;-)

Actually, it looks like that was added in OpenSSL 1.1; so it won't be
available on some systems where this code runs.

-- 
Colin Percival
Security Officer Emeritus, FreeBSD | The power to serve
Founder, Tarsnap | www.tarsnap.com | Online backups for the truly paranoid

**Comment by cperciva** [comment]
Should be fixed now that I've switched to using the OpenSSL 1.1 certificate checking functions.
