### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by zvory** [cperciva/bsdec2-image-upload#6]
Ubuntu 18.04 LTS

Ran `bmake`. Got a bunch of warnings, that were treated as errors, so compilation failed. Modified the compilation command that was printed to `stdout` to compile anyway.

Then ran `bmake` again. Got the following actual error:

```
lib/util/sslreq.c: In function ‘sslreq’:
lib/util/sslreq.c:74:32: error: ‘SO_NOSIGPIPE’ undeclared (first use in this function); did you mean ‘SO_OOBINLINE’?
  if (setsockopt(s, SOL_SOCKET, SO_NOSIGPIPE, &on, sizeof(on)))
                                ^~~~~~~~~~~~
                                SO_OOBINLINE
lib/util/sslreq.c:74:32: note: each undeclared identifier is reported only once for each function it appears in
*** Error code 1
```

That's probably because I'm on Ubuntu. I did assume I'm supposed to use `bmake`, really I just tried all the `make` commands I knew until one of them seemed to work.

**Comment by zvory** [comment]
Fixed (maybe?) using:
```
#include <signal.h>
```
...
```
    signal(SIGPIPE, SIG_IGN)
```

(if you can't tell i have no idea what i'm doing, thanks for making this tool btw)

**Comment by cperciva** [comment]
Yeah, that's the way to do it.  SO_NOSIGPIPE is a BSD thing, which was fine for me on FreeBSD but won't work on many other systems.

Please open a PR. :-)
